# Generated by Django 4.0 on 2021-12-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aflamna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='Type',
            field=models.CharField(choices=[('All', 'All'), ('New', 'New'), ('Trend', 'Trend')], default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
