# Generated by Django 4.0 on 2022-01-29 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aflamna', '0002_film_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='aflamna.film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='Type',
            field=models.CharField(choices=[('New', 'New'), ('Trend', 'Trend')], max_length=100),
        ),
    ]
