# Generated by Django 4.0 on 2022-01-29 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aflamna', '0003_alter_comment_film_alter_film_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='aflamna.film'),
        ),
    ]
