# Generated by Django 4.0 on 2022-01-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aflamna', '0005_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
