# Generated by Django 4.0 on 2022-01-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aflamna', '0006_remove_customuser_user_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
